server:
  port: 8181

spring:
  application:
    name: order-service
  profiles:
    active: order_service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: order-service,config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: order-service
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150