server:
  port: 8184

spring:
  application:
    name: customer-service
  profiles:
    active: customer_service
  config:
    import: 'configserver:'
  cloud:
    config:
      name: customer-service,config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: customer_service